### ISSUE TITLE
Regarding its execution on the Raspberry pi

### ISSUE THREAD

**Issue by aarushi0107** [MISTLab/ROSBuzz#4]
How will I implemented it on the on or off board micro controller using 3DR telemetry modules?

**Comment by dastoqc** [comment]
Hi,

Thank you for your interest in our research project.

Unfortunately I am not sure to grasp the meaning of your question. We did deployed ROSBuzz on RPI 2 and 3 successfully, mainly to control a fleet of 3DR Solo. As long as you get ROS Indigo or Kinetic up and running on your embedded system, ROSBuzz and Buzz are easy to set up.

We will be happy to help you if you have any specific issue with ROSBuzz deployment.

With regards,
David.
