### ISSUE TITLE
how to use buzz and ROS in simulation

### ISSUE THREAD

**Issue by PapadeStonne** [MISTLab/ROSBuzz#5]
hello MISTLAB,
I've been following your work  for some time now. I must say your work is state of art.
I am wondering how to USE Buzz and ROS in gazebo smulation. I'm quite confused about your ROSBuzz software architecture. Is there any detailed tutorial?
Many thanks!

**Comment by vivek-shankar** [comment]
Hi PapadeStonne, 

Thank you for your interest in Buzz and ROSBuzz. 
I would be more than happy to help you with that. 
If you are getting started with ROSBuzz, I would recommend having a look at the readme and our simulation setup here: https://git.mistlab.ca/dasto/drones 
If you have any specific questions after following the readme, please feel free to contact me. 

-Vivek
